
name: signseg

dependencies:
  - pip
  - python
  - matplotlib
  - seaborn
  - bokeh
  - numpy
  - tqdm
  - scipy
  - Pillow
  - tensorboard
  - h5py==2.10.0
  - pip:
    - zsvision
    - pympi_ling
    - opencv_python
    - beartype
    - ruptures
    - hickle
    - webvtt_py